apiVersion: apps/v1
kind: Deployment
metadata:
  name: tungstenfabric-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tungstenfabric-operator
  template:
    metadata:
      labels:
        name: tungstenfabric-operator
    spec:
      serviceAccountName: tungstenfabric-operator
      containers:
        - name: tungstenfabric-operator
          # Replace this with the built image name
          image: 192.168.1.46:5000/tf-operator:v0.0.2
          command:
          - tungstenfabric-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "tungstenfabric-operator"
